version: 0.2
env:
  parameter-store:
    DOCKER-HUB-USERNAME: /docker-hub-username
    DOCKER-HUB-PASSWORD: /docker-hub-password
phases:
  login:
    commands:
      - echo Logging into docker-hub...
      - docker login --username=$DOCKER-HUB-USERNAME --password=$DOCKER-HUB-PASSWORD
  install: # Install AWS cli, kubectl (needed for Helm) and Helm
    commands:
      - echo Installing dependencies...
      - apt install -y awscli git python3
      - curl -o aws-iam-authenticator https://amazon-eks.s3-us-west-2.amazonaws.com/1.12.7/2019-03-27/bin/linux/amd64/aws-iam-authenticator
      - chmod +x ./aws-iam-authenticator
      - mkdir -p ~/bin && cp ./aws-iam-authenticator ~/bin/aws-iam-authenticator && export PATH=~/bin:$PATH
      - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
      - chmod +x kubectl
      - mv ./kubectl /usr/local/bin/kubectl
      - wget https://get.helm.sh/helm-v3.4.1-linux-amd64.tar.gz -O helm.tar.gz; tar -xzf helm.tar.gz
      - chmod +x ./linux-amd64/helm
      - mv ./linux-amd64/helm /usr/local/bin/helm
  pre_build: # Add kubeconfig to access to EKS cluster
    commands:
      - echo Copying kube configuration...
      - mkdir ~/.kube/
      - cp ./terraform/kubeconfig_wolkstack ~/.kube/config
  build: # Build Docker image and tag it with the commit sha
    commands:
      - echo Building dockerfiles...
      - docker build ./apps/frontend -t $DOCKER_HUB_USERNAME/wolkstack:frontend -f ./apps/frontend/Dockerfile
      - docker build ./apps/backend -t $DOCKER_HUB_USERNAME/wolkstack:backend -f  ./apps/backend/Dockerfile
      - docker build ./apps/database -t $DOCKER_HUB_USERNAME/wolkstack:database -f  ./apps/database/Dockerfile

      - echo tagging dockerfiles...
      - docker tag $DOCKER_HUB_USERNAME/wolkstack:frontend $DOCKER_HUB_USERNAME/wolkstack:frontend
      - docker tag $DOCKER_HUB_USERNAME/wolkstack:backend $DOCKER_HUB_USERNAME/wolkstack:backend
      - docker tag $DOCKER_HUB_USERNAME/wolkstack:database $DOCKER_HUB_USERNAME/wolkstack:database
  post_build: # Push the Docker image to the ECR
    commands:
      - echo Pushing containers...
      - docker push $DOCKER_HUB_USERNAME/wolkstack:frontend
      - docker push $DOCKER_HUB_USERNAME/wolkstack:backend
      - docker push $DOCKER_HUB_USERNAME/wolkstack:database

      - echo Deploying applications...
      - helm upgrade wolkstack_apps ./helm/appChart
