apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: kuard
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/issuer: "letsencrypt-prod"

spec:
  tls:
    - hosts:
        - "{{ .Values.domain_name }}"
      secretName: wolkstack-deployment-secret
  rules:
    - host: "{{ .Values.Domain_name }}"
      http:
        paths:
          - backend:
              serviceName: kuard
              servicePort: 80
